# Generated by Django 2.1.3 on 2018-12-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='table',
            name='body',
        ),
        migrations.AddField(
            model_name='table',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='School',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='SchoolFee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='StartYear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
