# Generated by Django 2.1.3 on 2018-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20181201_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
