# Generated by Django 2.1.3 on 2018-12-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20181201_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='School',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='table',
            name='SchoolFee',
        ),
        migrations.RemoveField(
            model_name='table',
            name='StartYear',
        ),
        migrations.AddField(
            model_name='table',
            name='body',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
