# Generated by Django 2.1.3 on 2018-12-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20181201_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
    ]
