# Generated by Django 2.1.3 on 2018-12-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_remove_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(blank=True, max_length=500, null=True)),
                ('Location', models.TextField(blank=True, null=True)),
                ('SchoolFee', models.IntegerField(blank=True, null=True)),
                ('StartYear', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
