# Generated by Django 2.1.3 on 2018-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_table2'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='no',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='table2',
            name='no',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
